### ISSUE TITLE
add discord server link in contact section in README.md

### ISSUE THREAD

**Issue by Akshit1311** [DSCVITBHOPAL/Portfolio-Generator#5]
Discord Link for GDSC Vit Bhopal: https://discord.gg/p2zacmvq2S

**Comment by DiabolusGX** [comment]
The invite link is expired

**Comment by abhijeet007rocks8** [comment]
> The invite link is expired

It's updated now.

**Comment by raunakk07** [comment]
Hey, I want to work on this. Please assign me this.

**Comment by Akshit1311** [comment]
this issue has already been merged you can pick some other issue
